apiVersion: v1
kind: Service
metadata:
  namespace: cde-server-nightly
  name: cde-6-5-zookeeper
  labels:
    app: kafka
spec:
  ports:
  - port: 2181
    name: zookeeper-port
    targetPort: 2181
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  namespace: cde-server-nightly
  name: cde-6-5-kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Deployment
metadata:
  name: kafka
  namespace: cde-server-nightly
spec:
  replicas: 1
  selector:
    app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: ["cde-6-5-kafka.cde-server-nightly"]
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: cde-6-5-zookeeper:2181
      - name: zookeeper
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
